/* eslint-disable @next/next/no-page-custom-font */

import { Providers } from '@/components/common/provider';
import './globals.css';
import Navbar from "@/components/common/Navbar"
import { ToastContainer } from "react-toastify";
import Footer from "@/components/common/Footer";
export const metadata = {
  title: 'Saiful',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <head>
        <title>ishabee</title>

        <link
          rel="stylesheet"
          type="text/css"
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,600&family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,500;1,700&display=swap"
        />
        {/* <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        /> */}
      </head>
      <body>
        <Providers>
          <Navbar />
          <ToastContainer />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
